### PR TITLE
Monkey Business: Reinforcement learning meets neighborhood search for…

### PR DESCRIPTION
**Pull request by melkael**
… Virtual Network Embedding

### CODE REVIEW

**Comment by GeminiLight** [comment]
Great work! Thanks for your novel research on the VNE problem.

**Comment by melkael** [comment]
Thanks ! And thanks for adding my paper to your repo

**Comment by melkael** [comment]
If you want to add a link to the implementation (as well as the implementation of several other algorithms for the VNE), here is my github repo: https://github.com/melkael/vne

**Comment by GeminiLight** [comment]
This is an excellent suggestion that has been adopted!

**Pull request merged**
